### ISSUE TITLE
Overridden parent loggers

### ISSUE THREAD

**Issue by ryanhiebert** [brandon-rhodes/logging_tree#13]
There is an (undocumented, AFAICT) property on the loggers called `parent`. This points to the parent logger, skipping missing loggers up the chain.

Celery uses this property in an interesting way. The `get_task_logger` function overrides that `parent` attribute, so that those loggers will inherit its formatters (which add some nice, useful context about the worker the log was written from, what task was running, etc). Unfortunately, it meant that I saw some very strange behavior from this tool, which assumes that the parent logger will always be something from the beginning of the current logger.

**Comment by brandon-rhodes** [comment]
Thank you so much for letting me know about this — and for doing the investigation necessary to figure out what was going on when `logging_tree` showed one thing but the actual behavior you saw was something different! I hope that Celery’s abuse of the logging module’s internal data structures did not wind up burning a lot of your time before figuring out what was happening.

We should certainly update `logging_tree` as soon as possible so that users get shown that this is going on, something like:

```
   o<--[www]

       Broken .parent attribute! Points to -> "x.y.z"
       |
       o<--"www.status"
           Level DEBUG
           Handler File '/foo/log.txt'
           Handler <MyHandler>
```

To create a good test case, I would be interested in being able to see Celery doing this — in particular, I am wondering where the logger lives in the hierarchy that they are pointing other logger `.parent` attributes at. Is there a minimal little config file that would let me set up Celery and see the way it subverts these logging module internal data structures?

If not, could you paste in what `logging_tree` does show when Celery is active, along with a note about which `.parent` attributes have been changed and where they are pointing instead?

Then we'll write up a test case and add a special test to make sure that we let users know when the logging hierarchy has been damaged. Thanks again!

**Comment by ryanhiebert** [comment]
You don't need celery to see what I was describing.

Celery has a function called `get_task_logger`. Among other things, it creates a new logger with a given name (like `getLogger`), and overrides the `.parent` before it hands it back, setting it to the logger for `celery.task`.

The special behavior is entirely having to do with overriding that `parent` attribute. From what I can tell, that's done primarily to allow the logging formatting to be configured globally on the `celery.task` logger, and I suspect there's some magic in that formatter so that it can figure out where the task is currently running.

-----

This is a minimal example so that you can see how things look when the `parent` is overridden:

```pycon
>>> import logging, logging_tree
>>> a = logging.getLogger('a')
>>> b = logging.getLogger('b')
>>> bcd = logging.getLogger('b.c.d')
>>> a.level = logging.DEBUG
>>> b.level = logging.INFO
>>> bcd.parent = a
>>> logging_tree.printout()
<--""
   Level WARNING
   |
   o<--"a"
   |   Level DEBUG
   |
   o<--"b"
       Level INFO
       |
       o<--[b.c]
           |
           o<--"b.c.d"
               Level NOTSET so inherits level DEBUG
```

**Comment by brandon-rhodes** [comment]
Thank you! One last question: could you give me an example of the name one of these loggers has? I am curious where in the hierarchy it would have stood if Celery had not falsified its `.parent` reference. Is Celery moving it up, down, or sideways — from your example here, I suppose that it's pointing it over at an entirely separate hierarchy that it's not even part of?

**Comment by ryanhiebert** [comment]
Correct. In my particular case, I used `__name__` to construct it, so the name of the logger would have been `aspiredu.capture.tasks`, and it's parent was artificially set to `celery.task`.

**Comment by brandon-rhodes** [comment]
All right! I've released a new version 1.7 that (if I wrote the test right) correctly detects and reports on this situation.

Thank you VERY much, @ryanhiebert, for letting me know about this — I would never have run across this situation on my own, and logging_tree is now useful for a whole group of users who would otherwise have remained confused!

**Comment by ryanhiebert** [comment]
Thanks, the new version is great for providing this visibility.

For future visitors, I think this experiment proves that `.parent` is an implementation detail, and overriding it is a fundamentally broken thing to do:

```pycon
>>> import logging, logging_tree
>>> a = logging.getLogger('a')
>>> b = logging.getLogger('b')
>>> bcd = logging.getLogger('b.c.d')
>>> bcd.parent = a
>>> logging_tree.printout()
<--""
   Level WARNING
   |
   o<--"a"
   |   Level NOTSET so inherits level WARNING
   |
   o<--"b"
       Level NOTSET so inherits level WARNING
       |
       o<--[b.c]
           |
           o !-"b.c.d"
               Broken .parent! Messages propagate to "a"
               Level NOTSET so inherits level WARNING
>>> bc = logging.getLogger('b.c')
>>> logging_tree.printout()
<--""
   Level WARNING
   |
   o<--"a"
   |   Level NOTSET so inherits level WARNING
   |
   o<--"b"
       Level NOTSET so inherits level WARNING
       |
       o<--"b.c"
           Level NOTSET so inherits level WARNING
           |
           o<--"b.c.d"
               Level NOTSET so inherits level WARNING
```

If you override `.parent`, it may be invisibly rewritten if the _real_ parent (which hadn't been created yet) were created later, undoing your overriding of `.parent`. The `logging` module assumes that no-body else will be messing with that.

**Comment by brandon-rhodes** [comment]
Excellent point! I will use your comment as a reference if I ever hear questions about the `.parent` pointer that suggest that it might be changing out from under someone — thanks!
